spring:
  application.name: gateway
  datasource:
    url: jdbc:h2:file:./data/gateway
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
gateway:
  security: "database"  # "inmemory" ou "database"