
spring:
  application.name: stores
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/stores
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
server:
  port: 8082